language: r
r: bioc-devel
use_bioc: true
r_check_args: "--no-vignettes"
bioc_packages: DESeq2
before_install: 
  - cd DEVis
  - sudo apt-get install -y ghostscript
  - sudo apt-get install texlive-luatex
  - sudo apt-get install lmodern
  - sudo apt-get install luaotfload
  - sudo apt-get install texlive-fonts-recommended
